# Path to the processed dataset this approach will use
data_path: "data/sem_images/raw"
batch_size: 32
train_test_split: 0.8

# Training parameters
training:
  optimizer: "Adam" # Options: "Adam", "SGD"
  epochs: 50
  learning_rate: 0.001
  early_stopping:
    patience: 5
    metric: "val_loss" # Options: "val_loss", "val_f1", "val_auc"
    mode: "min" # Options: "min", "max"

validation:
  folds: 4
  start_train_percentage: 20
  end_train_percentage: 80
  train_percentage_step: 5
